language: python
python:
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenjpeg2

# command to install dependencies
install:
  - pip install numpy -q --use-mirrors
  - pip install matplotlib --use-mirrors
  - pip install . --use-mirrors
# command to run tests
script: 
  - "python -m unittest discover"
