sudo: true
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
    - NUMPY_VERSION=1.9.2 LXML_VERSION=3.4.4 SIX_VERSION=1.9.0
    - NUMPY_VERSION=1.8.2 LXML_VERSION=3.4.4 SIX_VERSION=1.9.0
    - NUMPY_VERSION=1.7.2 LXML_VERSION=3.0.2 SIX_VERSION=1.9.0

matrix:
    exclude:
    - python: 3.5
        - NUMPY_VERSION='1.8.2'
        - NUMPY_VERSION='1.9.2'

before_install:
  - bash travis-install-openjpeg.sh
  - sudo apt-get update -qq

# command to install dependencies
install:
    - pip install numpy==$NUMPY_VERSION lxml==$LXML_VERSION six==$SIX_VERSION contextlib2

# command to run tests
script:
  - python -m unittest discover

notifications:
  email: "john.g.evans.ne@gmail.com"
