language: python
python:
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python3-numpy
  - wget http://openjpeg.googlecode.com/files/openjpeg-1.5.0-Linux-x86_64.tar.gz
  - sudo tar -xvf openjpeg-1.5.0-Linux-x86_64.tar.gz --strip-components=1 -C /

# command to install dependencies
install: "pip install -r travis-requirements.txt --use-mirrors"

# command to run tests
# 2.7 should skip no more than 342 tests
# 3.3 should skip no more than 339 tests
script: "python -m unittest discover"

notifications:
  email: "john.g.evans.ne@gmail.com"
