#sudo: false                                                                        
language: python                                                                   
python:                                                                            
  - "2.7"                                                                          
  - "3.3"                                                                          
  - "3.4"                                                                          
                                                                                   
before_install:                                                                    
  - bash travis-install-openjpeg.sh                                                
  - sudo apt-get update -qq
  - sudo apt-get install -y libexempi3
                                                                                   
# command to install dependencies                                                  
install:                                                                           
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install lxml contextlib2 mock six python-xmp-toolkit ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install lxml numpy six python-xmp-toolkit ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install lxml numpy six python-xmp-toolkit ; fi
                                                                                   
# command to run tests                                                             
script:                                                                            
  - python -m unittest discover                                                    
                                                                                   
notifications:                                                                     
  email: "john.g.evans.ne@gmail.com"                                                                   
