language: python
python:
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenjpeg2
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python3-numpy

# command to install dependencies
install:
  - pip install . --use-mirrors
# command to run tests
script: 
  - "python -m unittest discover"
