language: python
matrix:
    fast_finish: true
    include:
    - python: 2.7
      env:
          - JOB_NAME "27_latest"
          - JOB_TAG=27_latest
    - python: 3.3
      env:
          - JOB_NAME "33"
          - JOB_TAG=33
    - python: 3.4
      env:
          - JOB_NAME "34_latest"
          - JOB_TAG=34_latest
    - python: 3.5
      env:
          - JOB_NAME "35_latest"
          - JOB_TAG=35_latest
    - python: 3.5
      env:
          - JOB_NAME "35_no_openjpeg"
          - JOB_TAG=35_no_openjpeg
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - ci/install_travis.sh
  - python setup.py install
  - conda config --append channels conda-forge
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install --file ci/"$JOB_TAG".txt

script:
  - python -m unittest discover
