sudo: true
language: python

matrix:
    include:
    - python: 2.7
      env:
      - JOB_NAME: "27_eldest"
      - NUMPY_VERSION=1.7.2
      - LXML_VERSION=3.0.2
      - NO_OPENJPEG=0
    - python: 2.7
      env:
      - JOB_NAME: "27_np182"
      - NUMPY_VERSION=1.8.2
      - LXML_VERSION=3.4.4
      - NO_OPENJPEG=0
    - python: 2.7
      env:
      - JOB_NAME: "27_np192"
      - NUMPY_VERSION=1.9.2
      - LXML_VERSION=3.4.4
      - NO_OPENJPEG=0
    - python: 2.7
      env:
      - JOB_NAME: "27_np_latest"
      - NUMPY_VERSION=1.10.1
      - LXML_VERSION=3.4.4
      - NO_OPENJPEG=0
    - python: 3.3
      env:
      - JOB_NAME: "33"
      - NUMPY_VERSION=1.7.2
      - LXML_VERSION=3.0.2
      - NO_OPENJPEG=0
    - python: 3.4
      env:
      - JOB_NAME: "34"
      - NUMPY_VERSION=1.9.2
      - LXML_VERSION=3.4.4
      - NO_OPENJPEG=0
    - python: 3.5
      env:
      - JOB_NAME: "35_latest"
      - NUMPY_VERSION=1.10.1
      - LXML_VERSION=3.4.4
      - NO_OPENJPEG=0
    - python: 3.5
      env:
      - JOB_NAME: "no_openjpeg"
      - NUMPY_VERSION=1.10.1
      - LXML_VERSION=3.4.4
      - NO_OPENJPEG=1
    
before_install:
  - bash travis-install-openjpeg.sh
  - sudo apt-get update -qq
  - sudo apt-get install libexempi3

# command to install dependencies
install:
    - pip install numpy==$NUMPY_VERSION lxml==$LXML_VERSION python-xmp-toolkit six contextlib2

# command to run tests
script:
  - python -m unittest discover

notifications:
  email: "john.g.evans.ne@gmail.com"
